Traceback (most recent call last):
  File "/KWH/datalogger/transceive/sms/smsParse.py", line 210, in <module>
    subprocess.Popen([delPath, messNum[i]])
IndexError: list index out of range
